sensor_msgs/Image frame
hri_msgs/FacePosition position
float32 score
---
sensor_msgs/Image face_aligned
float32[] features
std_msgs/String classified
float32 distance
int32 pos
float32 recognition_time