string provider
string model
string prompt_system
string messages_json # cambiar esto a un mensaje propio de ros que sea content y role algo asi para cada msg
string user_input
string parameters_json # cambiar esto a temperature y max_tokens
---
string response
string provider_used
string model_used
string message
bool success